remote_theme: hardpool/hardpool-flat

# Site Settings
title                     : "Hardik Dabhi"
title_separator           : "|"
favicon                   : /test/assets/fav.ico
csstheme                  : "site"
scss                      : "colors"

# Site SEO
seo:
  gtmid: GTM-M3MXT24

# Site Header
main_logo                 : "https://s.gravatar.com/avatar/57ab9065cb1800ee75c6a34f27d78707?s=192"
name                      : "Hardik Dabhi"
description               : "Software Developer, Applications<span class='mx-2'>&#8226;</span><a target='_blank' href='https://github.com/hardikdabhi'>@hardikdabhi</a>"

# Site Footer
copyright: "Developed using Jekyll & Github pages"
footer:
  insta_at: 2321794898.c625d4b.52d85f33c6074769a1052765b092bc06
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: https://github.com/hardikdabhi/
    - label: "Npm"
      icon: "fab fa-fw fa-npm"
      url: https://www.npmjs.com/~hardikdabhi
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-f"
      url: https://www.facebook.com/dabhi.hardik
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: https://www.instagram.com/hardikdabhi22/

# Sass/SCSS
sass:
  style: compressed
  sass_dir: sass

# Reading Files
include:
  - _pages

# config
permalink: /:title